### ISSUE TITLE
Packages aren't published

### ISSUE THREAD

**Issue by nivida** [status-im/react-native-status-keycard#12]
I've tried to install the package with ``npm`` and the ``react-native`` CLI.

commands:
```
react-native link react-native-status-keycard

npm install react-native-status-keycard --save
```

Both packages couldn't be found.

**Comment by dmitryn** [comment]
Hey @nivida!
We used to link this library using git, but now package has been also published to npmjs https://www.npmjs.com/package/react-native-status-keycard

I'm also going to add some docs to README
