### ISSUE TITLE
Can not build RN app with react-native-status-keycard

### ISSUE THREAD

**Issue by misovan** [status-im/react-native-status-keycard#17]
When trying to build fresh new React native app with installed and linked keycard package, I am getting the following errors:

`Could not determine the dependencies of task ':app:preDebugBuild'.
Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
Could not find com.github.status-im.status-keycard-java:android:2.2.1.
Searched in the following locations: 
...............
Required by:
         project :app > project :react-native-status-keycard`

I tried both automated and manual linking according to Readme.
I then added jitpack to the repositories section in android/build.gradle file, and looks like build move forward, however I got another error I am unable to solve:

`Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
D:\pathtoproject\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:17: error: cannot find symbol
import com.reactlibrary.RNStatusKeycardPackage;`

Looks like expected com.reactlibrary.RNStatusKeycardPackage is different namespace then what is mentioned to be imported in the manual installation docs (im.status.ethereum.keycard.RNStatusKeycardPackage) or might there be another issues in my setup I can not grasp? Help appreciated.

**Comment by TrustTheBoy** [comment]
change to `import im.status.ethereum.keycard.RNStatusKeycardPackage;`

**Comment by misovan** [comment]
Thanks, I found that the com.reactlibrary was declared in AndroidManifest.xml of react-native-status-keycard package. After I fixed it there, I am able to build the test react application.

**Comment by misovan** [comment]
To provide full info to someone else trying, to make a working RN app I had to as well add
```
    @Override
    public boolean canOverrideExistingModule() {
        return true;
    }
```
to RNStatusKeycardModule.java constructor. Perhaps relates to changes in newer versions of RN's package management.
