### ISSUE TITLE
Change error handling in getApplicationInfo

### ISSUE THREAD

**Issue by bitgamma** [status-im/react-native-status-keycard#28]
at the moment, the Java SDK throws an IOException when autoOpenSecureChannel or autoPair fails. This is the same exception throw when connection to the card fails. 

In getApplicationInfo this exception is caught in order to determine if the pairing is valid or not but no distinction is made between invalid authentication and connection lost. After updating the SDK to separate pure IO errors from unexpected card responses, these two cases can be handled independently.

if an IOException is thrown, it is let bubble up to status-react, which should interpret it as connection lost (and probably just prompt the user again to connect the card)

only if an APDUException is thrown during openSecureChannel, getApplicationInfo's current behavior will apply (catching and setting "paired?" to false). This should then be interpreted as missing or invalid pairing. In that case the puk and pin retry counters won't be available, because they are only retrievable after opening a secure channel.

The changes to this component are not complex, however implementing them changes the behaviour under error conditions of

* getApplicationInfo
* pair

pair will also automatically gain a differentiation between card connection lost and invalid pairing by throwing IOException and APDUException respectively. This can be used in status-react to react differently to these error conditions.

Because of these changes in behavior, the error scenarios involving these two methods should be tested again to make sure the approriate behavior still applies.

**Comment by guylouis** [comment]
SDK changes needed to fix this are here https://github.com/status-im/react-native-status-keycard/pull/29

**Comment by bitgamma** [comment]
fixed by #29
